---
- name: Building the firstname-scripts docker image
  hosts: all
  become: true
  tasks:
   - name: build the image
     docker_image:
        name: built-by-jenkins-ansible
        path: "{{workdir}}"
        

