---
- name: Building the firstname-scripts docker image
  hosts: localhost
  tasks:
   - name: remove existing image
     docker_image:
       name: built-by-jenkins-ansible
       state: absent
   - name: build the image
     docker_image:
        name: built-by-jenkins-ansible
        path: "{{workdir}}"
        archive_path: "built-by-jenkins-ansible.tar"
        

