---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create S3 test bucket.
    local_action:
      module: s3
      bucket: 'upload-from-jenkins'
      mode: create
      region: 'us-east-1'
  - name: Simple PUT operation
    s3_sync:
      bucket: 'upload-from-jenkins'
      file_root: "{{ image_root_folder }}"
      include: "*.tar"
      mode: push
      permission: public-read
    
