---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create S3 test bucket.
    s3:
      bucket: 'upload-from-jenkins'
      mode: create
      region: 'us-east-1'
  - name: Simple PUT operation
    s3:
      bucket: 'upload-from-jenkins'
      object: built-by-jenkins-ansible.tar
      src: built-by-jenkins-ansible.tar
      mode: put
      region: 'us-east-1'
